######################################################################
# Automatically generated by qmake (3.0) sam. janv. 21 20:30:12 2017
######################################################################

TEMPLATE = app
TARGET = qt_test
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += test_window.hpp
SOURCES += test1.cpp test_window.cpp
